services:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d         
      - ./wwwhtml:/usr/share/nginx/html       
      - ./lognginx:/var/log/nginx             
    ports:
      - "8021:80"
    environment:
      - NGINX_PORT=80
